apiVersion: v1
kind: Service
metadata:
  name: harness-coordinator
  namespace: harness
spec:
  selector:
    app: harness-coordinator
  ports:
    - name: http
      port: 8877
      targetPort: 8877
