apiVersion: v1
kind: Service
metadata:
  name: new-horizons-metrics
  namespace: new-horizons
  labels:
    app: new-horizons
    app.kubernetes.io/component: metrics
spec:
  selector:
    app: new-horizons
  ports:
    - name: metrics
      port: 9109
      targetPort: metrics
      protocol: TCP
