---
# Let's Encrypt Staging (for testing, avoids rate limits)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: matt@mtgibbs.xyz
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
# Let's Encrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: matt@mtgibbs.xyz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
# Self-signed issuer (fallback/legacy)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# CA Certificate for self-signed fallback
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pi-cluster-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: pi-cluster-ca
  secretName: pi-cluster-ca-secret
  duration: 87600h # 10 years
  renewBefore: 8760h # 1 year
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Self-signed CA issuer (fallback)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pi-cluster-ca-issuer
spec:
  ca:
    secretName: pi-cluster-ca-secret
