apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ollama-config
  namespace: ollama
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: ollama-config
    creationPolicy: Owner
  data:
    - secretKey: OLLAMA_MODEL
      remoteRef:
        key: CARL/ollama_model
