---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.6.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: alertmanager-discord
      valuesKey: webhook-url
      targetPath: alertmanager.config.receivers[0].discord_configs[0].webhook_url
  values:
    # Grafana settings
    grafana:
      admin:
        existingSecret: grafana-secret
        passwordKey: admin-password
      # Use Recreate strategy for RWO PVC compatibility
      deploymentStrategy:
        type: Recreate
      persistence:
        enabled: true
        size: 1Gi
        storageClassName: local-path
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      # ClusterIP for ingress access
      service:
        type: ClusterIP
        port: 3000
      # Configure for subdomain access
      grafana.ini:
        server:
          domain: "grafana.lab.mtgibbs.dev"
          root_url: "https://grafana.lab.mtgibbs.dev"
      # Additional datasources
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki.log-aggregation.svc.cluster.local:3100
          access: proxy
          isDefault: false

    # Prometheus settings
    prometheus:
      prometheusSpec:
        retention: 7d
        retentionSize: 2GB
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

    # Alertmanager - send alerts to Discord
    alertmanager:
      enabled: true
      alertmanagerSpec:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['alertname', 'namespace']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          receiver: discord
          routes:
            # Silence noisy/expected alerts
            - receiver: 'null'
              matchers:
                - alertname =~ "Watchdog|KubeMemoryOvercommit"
            # Critical alerts get sent immediately
            - receiver: discord
              matchers:
                - severity = critical
              group_wait: 10s
              repeat_interval: 1h
        receivers:
          - name: discord
            discord_configs:
              - send_resolved: true
                title: '{{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }} {{ .CommonLabels.alertname }}'
                message: |
                  {{ range .Alerts }}
                  **Status:** {{ .Status | toUpper }}
                  **Severity:** {{ .Labels.severity }}
                  **Description:** {{ .Annotations.description }}
                  {{ end }}
          - name: 'null'  # Silence receiver

    # Node exporter - lightweight
    nodeExporter:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi

    # Kube-state-metrics
    kubeStateMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Prometheus operator
    prometheusOperator:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

    # Disable components not needed for single-node learning cluster
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
