apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-homelab
rules:
  # Read-only: Core resources
  - apiGroups: [""]
    resources: [pods, pods/log, services, nodes, events, configmaps, persistentvolumeclaims, namespaces]
    verbs: [get, list, watch]

  # Read-only: Apps
  - apiGroups: ["apps"]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list, watch]

  # Read-only: Flux
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [kustomizations]
    verbs: [get, list, watch]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [helmreleases]
    verbs: [get, list, watch]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [gitrepositories, helmrepositories, helmcharts]
    verbs: [get, list, watch]
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: [imagerepositories, imagepolicies, imageupdateautomations]
    verbs: [get, list, watch]

  # Read-only: Cert-manager
  - apiGroups: ["cert-manager.io"]
    resources: [certificates, certificaterequests, issuers, clusterissuers, challenges, orders]
    verbs: [get, list, watch]

  # Read-only: External Secrets
  - apiGroups: ["external-secrets.io"]
    resources: [externalsecrets, clustersecretstores, secretstores]
    verbs: [get, list, watch]

  # Read-only: Networking
  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses, ingressclasses]
    verbs: [get, list, watch]

  # Read-only: Tailscale
  - apiGroups: ["tailscale.com"]
    resources: [connectors, proxyclasses]
    verbs: [get, list, watch]

  # Read-only: Batch (backup jobs)
  - apiGroups: ["batch"]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch]

  # Read-only: Metrics
  - apiGroups: ["metrics.k8s.io"]
    resources: [nodes, pods]
    verbs: [get, list]

  # Action: Restart deployments (rollout restart via annotation patch)
  - apiGroups: ["apps"]
    resources: [deployments]
    verbs: [patch]

  # Action: Trigger Flux reconcile (annotation patch)
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [kustomizations]
    verbs: [patch]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [helmreleases]
    verbs: [patch]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [gitrepositories]
    verbs: [patch]

  # Action: Force ExternalSecret refresh (annotation patch)
  - apiGroups: ["external-secrets.io"]
    resources: [externalsecrets]
    verbs: [patch]

  # Action: Create manual backup jobs
  - apiGroups: ["batch"]
    resources: [jobs]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-homelab
subjects:
  - kind: ServiceAccount
    name: mcp-homelab
    namespace: mcp-homelab
roleRef:
  kind: ClusterRole
  name: mcp-homelab
  apiGroup: rbac.authorization.k8s.io
---
# Namespace-scoped: pod exec in jellyfin only (for metadata fix)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-homelab-jellyfin-exec
  namespace: jellyfin
rules:
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-homelab-jellyfin-exec
  namespace: jellyfin
subjects:
  - kind: ServiceAccount
    name: mcp-homelab
    namespace: mcp-homelab
roleRef:
  kind: Role
  name: mcp-homelab-jellyfin-exec
  apiGroup: rbac.authorization.k8s.io
---
# Namespace-scoped: pod exec in pihole (for DNS query testing)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-homelab-pihole-exec
  namespace: pihole
rules:
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-homelab-pihole-exec
  namespace: pihole
subjects:
  - kind: ServiceAccount
    name: mcp-homelab
    namespace: mcp-homelab
roleRef:
  kind: Role
  name: mcp-homelab-pihole-exec
  apiGroup: rbac.authorization.k8s.io
---
# Namespace-scoped: pod exec in mcp-homelab (for debug-agent tools)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-homelab-debug-exec
  namespace: mcp-homelab
rules:
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-homelab-debug-exec
  namespace: mcp-homelab
subjects:
  - kind: ServiceAccount
    name: mcp-homelab
    namespace: mcp-homelab
roleRef:
  kind: Role
  name: mcp-homelab-debug-exec
  apiGroup: rbac.authorization.k8s.io
