apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: carl-canvas-api
  namespace: carl
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: carl-canvas-api
    creationPolicy: Owner
  data:
    - secretKey: CANVAS_API_TOKEN
      remoteRef:
        key: Canvas-API/token
    - secretKey: CANVAS_BASE_URL
      remoteRef:
        key: Canvas-API/base_url
    - secretKey: CANVAS_STUDENT_ID
      remoteRef:
        key: Canvas-API/student_id
