apiVersion: v1
kind: ConfigMap
metadata:
  name: autokuma-monitors
  namespace: uptime-kuma
data:
  # Discord notification - referenced by monitors for alerts
  # Uses __notification_ prefix for AutoKuma notification management
  __notification_discord.json: |
    {
      "name": "Discord Alerts",
      "type": "discord",
      "isDefault": true,
      "discordWebhookUrl": "${DISCORD_WEBHOOK_URL}"
    }
  # Each file is a separate monitor - filename (without .json) becomes the monitor ID
  pihole-dns.json: |
    {
      "type": "port",
      "name": "Pi-hole DNS",
      "hostname": "192.168.1.55",
      "port": 53,
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  pihole-admin.json: |
    {
      "type": "http",
      "name": "Pi-hole Admin",
      "url": "https://pihole.lab.mtgibbs.dev/admin/",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  grafana.json: |
    {
      "type": "http",
      "name": "Grafana",
      "url": "https://grafana.lab.mtgibbs.dev/api/health",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  prometheus.json: |
    {
      "type": "http",
      "name": "Prometheus",
      "url": "http://kube-prometheus-kube-prome-prometheus.monitoring.svc:9090/-/healthy",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  unbound-dns.json: |
    {
      "type": "port",
      "name": "Unbound DNS",
      "hostname": "unbound.pihole.svc.cluster.local",
      "port": 5335,
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  k3s-api.json: |
    {
      "type": "port",
      "name": "K3s API",
      "hostname": "192.168.1.55",
      "port": 6443,
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  uptime-kuma.json: |
    {
      "type": "http",
      "name": "Uptime Kuma",
      "url": "https://status.lab.mtgibbs.dev/",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  homepage.json: |
    {
      "type": "http",
      "name": "Homepage",
      "url": "https://home.lab.mtgibbs.dev/",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  unifi.json: |
    {
      "type": "http",
      "name": "Unifi Controller",
      "url": "https://unifi.lab.mtgibbs.dev/",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  synology.json: |
    {
      "type": "http",
      "name": "Synology NAS",
      "url": "https://nas.lab.mtgibbs.dev/",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  jellyfin.json: |
    {
      "type": "http",
      "name": "Jellyfin",
      "url": "https://jellyfin.lab.mtgibbs.dev/health",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
  immich.json: |
    {
      "type": "http",
      "name": "Immich",
      "url": "https://immich.lab.mtgibbs.dev/api/server/ping",
      "interval": 60,
      "retryInterval": 30,
      "maxretries": 3
    }
