apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptime-kuma-secret
  namespace: uptime-kuma
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: uptime-kuma/username
    - secretKey: password
      remoteRef:
        key: uptime-kuma/password
