apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-kuma-setup-script
  namespace: uptime-kuma
data:
  setup.py: |
    #!/usr/bin/env python3
    import os
    import json
    import time
    import sys
    from uptime_kuma_api import UptimeKumaApi, MonitorType

    KUMA_URL = os.environ.get("KUMA_URL", "http://uptime-kuma:3001")
    USERNAME = os.environ["KUMA_USERNAME"]
    PASSWORD = os.environ["KUMA_PASSWORD"]
    MONITORS_FILE = "/config/monitors.json"

    def wait_for_kuma(api, max_retries=30):
        """Wait for Uptime Kuma to be ready"""
        for i in range(max_retries):
            try:
                api.connect(wait=True)
                print(f"Connected to Uptime Kuma at {KUMA_URL}")
                return True
            except Exception as e:
                print(f"Waiting for Uptime Kuma... ({i+1}/{max_retries}): {e}")
                time.sleep(10)
        return False

    def setup_account(api):
        """Set up admin account if this is first run"""
        try:
            # Check if setup is needed
            if api.need_setup():
                print("First run detected, creating admin account...")
                api.setup(USERNAME, PASSWORD)
                print("Admin account created")
            else:
                print("Admin account already exists, logging in...")
                api.login(USERNAME, PASSWORD)
                print("Logged in successfully")
        except Exception as e:
            # Try logging in if setup fails (account might already exist)
            print(f"Setup check failed, trying login: {e}")
            api.login(USERNAME, PASSWORD)
            print("Logged in successfully")

    def get_monitor_type(type_str):
        """Convert string type to MonitorType enum"""
        type_map = {
            "http": MonitorType.HTTP,
            "port": MonitorType.PORT,
            "ping": MonitorType.PING,
            "keyword": MonitorType.KEYWORD,
            "dns": MonitorType.DNS,
            "docker": MonitorType.DOCKER,
            "push": MonitorType.PUSH,
            "steam": MonitorType.STEAM,
            "gamedig": MonitorType.GAMEDIG,
            "mqtt": MonitorType.MQTT,
            "sqlserver": MonitorType.SQLSERVER,
            "postgres": MonitorType.POSTGRES,
            "mysql": MonitorType.MYSQL,
            "mongodb": MonitorType.MONGODB,
            "radius": MonitorType.RADIUS,
            "redis": MonitorType.REDIS,
        }
        return type_map.get(type_str.lower(), MonitorType.HTTP)

    def create_monitors(api, monitors):
        """Create monitors from config"""
        existing = {m["name"]: m for m in api.get_monitors()}

        for monitor in monitors:
            name = monitor["name"]
            if name in existing:
                print(f"Monitor '{name}' already exists, skipping")
                continue

            monitor_type = get_monitor_type(monitor.pop("type"))

            # Map config fields to API fields
            kwargs = {"type": monitor_type}

            # Common fields
            if "name" in monitor:
                kwargs["name"] = monitor["name"]
            if "interval" in monitor:
                kwargs["interval"] = monitor["interval"]
            if "retryInterval" in monitor:
                kwargs["retryInterval"] = monitor["retryInterval"]
            if "maxretries" in monitor:
                kwargs["maxretries"] = monitor["maxretries"]

            # Type-specific fields
            if "url" in monitor:
                kwargs["url"] = monitor["url"]
            if "hostname" in monitor:
                kwargs["hostname"] = monitor["hostname"]
            if "port" in monitor:
                kwargs["port"] = monitor["port"]
            if "keyword" in monitor:
                kwargs["keyword"] = monitor["keyword"]
            if "ignoreTls" in monitor:
                kwargs["ignoreTls"] = monitor["ignoreTls"]

            try:
                api.add_monitor(**kwargs)
                print(f"Created monitor: {name}")
            except Exception as e:
                print(f"Failed to create monitor '{name}': {e}")

    def main():
        # Load monitors config
        with open(MONITORS_FILE) as f:
            monitors = json.load(f)

        print(f"Loaded {len(monitors)} monitor definitions")

        api = UptimeKumaApi(KUMA_URL)

        if not wait_for_kuma(api):
            print("Failed to connect to Uptime Kuma")
            sys.exit(1)

        setup_account(api)
        create_monitors(api, monitors)

        api.disconnect()
        print("Setup complete!")

    if __name__ == "__main__":
        main()
---
apiVersion: batch/v1
kind: Job
metadata:
  name: uptime-kuma-setup
  namespace: uptime-kuma
  annotations:
    # Re-run this job when config changes
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-kuma
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Uptime Kuma to be ready..."
              until wget -q --spider http://uptime-kuma:3001; do
                echo "Uptime Kuma not ready, waiting..."
                sleep 5
              done
              echo "Uptime Kuma is ready!"
      containers:
        - name: setup
          image: python:3.11-slim
          command:
            - sh
            - -c
            - |
              pip install --quiet uptime-kuma-api websocket-client &&
              python /scripts/setup.py
          env:
            - name: KUMA_URL
              value: "http://uptime-kuma:3001"
            - name: KUMA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-secret
                  key: username
            - name: KUMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-secret
                  key: password
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: config
              mountPath: /config
      volumes:
        - name: scripts
          configMap:
            name: uptime-kuma-setup-script
        - name: config
          configMap:
            name: uptime-kuma-monitors
