apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: family-board
  namespace: family-board
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "board.lab.mtgibbs.dev"
      secretName: family-board-tls
  rules:
    - host: "board.lab.mtgibbs.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: family-board
                port:
                  number: 80
