apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: exit-node-secrets
  namespace: private-exit-node
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: exit-node-secrets
    creationPolicy: Owner
  data:
    - secretKey: wg-private-key
      remoteRef:
        key: private-exit-node/wg-private-key
    - secretKey: wg-peer-public-key
      remoteRef:
        key: private-exit-node/wg-peer-public-key
    - secretKey: ss-password
      remoteRef:
        key: private-exit-node/ss-password
    - secretKey: vps-ip
      remoteRef:
        key: private-exit-node/vps-ip
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: private-exit-node
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"mtgibbs","password":"{{ .token }}","auth":"{{ printf "mtgibbs:%s" .token | b64enc }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: ghcr-read-token/token
