apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: n8n-secret
    creationPolicy: Owner
  data:
    # Encryption key for credentials stored in n8n
    # CRITICAL: Back this up - losing it means losing access to all stored credentials
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n/encryption-key
