---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: flux-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"mtgibbs","password":"{{ .token }}","auth":"{{ printf "mtgibbs:%s" .token | b64enc }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: ghcr-read-token/token
