---
# 1. External Secrets Operator - installs the operator and CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/pi-k3s/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
# 2. Secret Store config - depends on ESO CRDs being installed
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  interval: 10m
  path: ./clusters/pi-k3s/external-secrets-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
# 3. Pi-hole stack - depends on secret store for ExternalSecrets
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-config
  interval: 10m
  path: ./clusters/pi-k3s/pihole
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
