apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secret
  namespace: mealie
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: mealie-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: mealie/db-password
