apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - namespace.yaml
  - external-secret.yaml
  - pvc.yaml
  - postgresql.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ai-provider-bootstrap.yaml
  - ai-prompts.yaml
