apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mirror-token
  namespace: backup-jobs
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-mirror-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: github-mirror-token/token
