---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-backup
  namespace: backup-jobs
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-db-password
  namespace: backup-jobs
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: romm-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: romm/db-password
