apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-backup
  namespace: backup-jobs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: synology-backup-nfs
  storageClassName: ""
