---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: backup-jobs
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-password
  namespace: backup-jobs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: immich-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: immich/db-password
