apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-credentials
  namespace: backup-jobs
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: unifi/username
    - secretKey: password
      remoteRef:
        key: unifi/password
