---
# Endpoints for Plex Server (external Pi 3)
apiVersion: v1
kind: Endpoints
metadata:
  name: plex-external
  namespace: external-services
subsets:
  - addresses:
      - ip: 192.168.1.53
    ports:
      - port: 32400
        name: http
---
# Service pointing to the external endpoints
apiVersion: v1
kind: Service
metadata:
  name: plex-external
  namespace: external-services
spec:
  ports:
    - port: 32400
      targetPort: 32400
      name: http
---
# Ingress with TLS termination
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "plex.lab.mtgibbs.dev"
      secretName: plex-tls
  rules:
    - host: "plex.lab.mtgibbs.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-external
                port:
                  number: 32400
