apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanuparr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanuparr
  template:
    metadata:
      labels:
        app: cleanuparr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - pi5-worker-1
      containers:
        - name: cleanuparr
          image: ghcr.io/recyclarr/cleanuparr:latest
          env:
            - name: PUID
              value: "1029"
            - name: PGID
              value: "100"
            - name: TZ
              value: America/Chicago
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: config
          configMap:
            name: cleanuparr-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cleanuparr-config
  namespace: media
data:
  cleanuparr.yml: |
    # Cleanuparr configuration
    # Blocks dangerous file extensions
    blocked_extensions:
      - .exe
      - .msi
      - .bat
      - .cmd
      - .ps1
      - .vbs
      - .js
      - .jse
      - .wsf
      - .wsh
      - .scr
      - .pif
      - .com
      - .dll
      - .jar
      - .lnk
      - .hta
      - .reg
