---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      # Use DaemonSet for single-node cluster
      kind: DaemonSet

      # Use hostPort to bind directly to node ports
      hostPort:
        enabled: true
        ports:
          http: 8080   # Port 80 is used by Pi-hole
          https: 443

      # Disable HTTP (redirect) service since port 80 is taken
      service:
        enabled: true
        type: ClusterIP

      # Resource limits for Pi
      resources:
        requests:
          cpu: 50m
          memory: 90Mi
        limits:
          cpu: 500m
          memory: 256Mi

      # Enable Prometheus metrics
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus

      # Admission webhooks
      admissionWebhooks:
        enabled: true

    # Default backend not needed
    defaultBackend:
      enabled: false
