apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secret
  namespace: romm
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: romm-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWD
      remoteRef:
        key: romm/db-password
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: romm/db-root-password
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: romm/auth-secret-key
