apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-games-nfs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nolock
    - rsize=1048576
    - wsize=1048576
  nfs:
    server: storage.lab.mtgibbs.dev
    path: /cluster/games
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-games
  namespace: romm
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: romm-games-nfs
  resources:
    requests:
      storage: 500Gi
