apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: https://api.1password.com
      vaults:
        pi-cluster: 1
      auth:
        serviceAccountTokenSecretRef:
          name: onepassword-service-account
          namespace: external-secrets
          key: token
