---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/immich-app/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  values:
    # ========================================
    # Machine Learning - DISABLED for Pi 5
    # ========================================
    machine-learning:
      enabled: false

    # ========================================
    # Immich Server
    # ========================================
    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                tag: v1.123.0
              env:
                TZ: "America/New_York"
                REVERSE_GEOCODING_PRECISION: "1"
                # Use pgvector extension (vector 0.8.1 is installed)
                DB_VECTOR_EXTENSION: pgvector
                # External PostgreSQL connection
                DB_HOSTNAME: immich-postgresql
                DB_DATABASE_NAME: immich
                DB_USERNAME: immich
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-secret
                      key: DB_PASSWORD
                # Redis/Valkey connection (built-in valkey)
                REDIS_HOSTNAME: immich-valkey
                REDIS_PORT: "6379"
                # JWT secret for session management
                IMMICH_SECRET:
                  valueFrom:
                    secretKeyRef:
                      name: immich-secret
                      key: IMMICH_SECRET
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: 2000m
                  memory: 2Gi
      ingress:
        main:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          hosts:
            - host: immich.lab.mtgibbs.dev
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
          tls:
            - hosts:
                - immich.lab.mtgibbs.dev
              secretName: immich-tls

    # ========================================
    # Photo Library Persistence (NFS)
    # ========================================
    immich:
      persistence:
        library:
          existingClaim: immich-library

    # ========================================
    # Built-in Valkey (Redis replacement)
    # ========================================
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 200m
                  memory: 128Mi
      persistence:
        data:
          enabled: true
          type: persistentVolumeClaim
          size: 1Gi
          storageClass: local-path
          accessMode: ReadWriteOnce
