---
# Service to expose metrics ports
apiVersion: v1
kind: Service
metadata:
  name: immich-metrics
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-metrics
    app.kubernetes.io/instance: immich
spec:
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: immich
  ports:
    - name: api-metrics
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: microservices-metrics
      port: 8082
      targetPort: 8082
      protocol: TCP
---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    release: kube-prometheus  # Match Prometheus Operator selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-metrics
      app.kubernetes.io/instance: immich
  namespaceSelector:
    matchNames:
      - immich
  endpoints:
    - port: api-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
    - port: microservices-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
