---
# Tailscale Helm repository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
# Tailscale Operator - manages Tailscale resources in the cluster
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.92.5"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    # OAuth credentials from 1Password via ExternalSecret
    oauth:
      clientId:
        secretKeyRef:
          name: operator-oauth
          key: client_id
      clientSecret:
        secretKeyRef:
          name: operator-oauth
          key: client_secret
    # Operator config
    operatorConfig:
      defaultTags:
        - tag:k8s-operator
    # Proxy config
    proxyConfig:
      defaultProxyClass: pi-cluster
      defaultTags: "tag:k8s"
