apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: WEBPASSWORD
      remoteRef:
        key: pihole/password    # SDK format: item/field
