apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-secondary
  namespace: pihole
  annotations:
    # Prevent Flux from ever deleting this PVC (protects data)
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-secondary
  namespace: pihole
  annotations:
    # Prevent Flux from ever deleting this PVC (protects data)
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
