apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-secret
  namespace: matrix
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: matrix-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_PASSWORD: "{{ .db-password }}"
        homeserver-secrets.yaml: |
          database:
            password: "{{ .db-password }}"
          registration_shared_secret: "{{ .registration-shared-secret }}"
          macaroon_secret: "{{ .macaroon-secret }}"
          form_secret: "{{ .form-secret }}"
  data:
    - secretKey: db-password
      remoteRef:
        key: matrix/db-password
    - secretKey: registration-shared-secret
      remoteRef:
        key: matrix/registration-shared-secret
    - secretKey: macaroon-secret
      remoteRef:
        key: matrix/macaroon-secret
    - secretKey: form-secret
      remoteRef:
        key: matrix/form-secret