apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgresql-data
  namespace: matrix
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled # Flux won't delete -> protects data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: matrix
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled # Flux won't delete -> protects data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi